name: Bug report
description: Report a reproducible documentation or guidance problem
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Affected Location
      description: File/section/phase reference.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Guidance
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Contradiction, broken links, or unclear instructions.
